# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voiceguard_pb2 as voiceguard__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voiceguard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceGuardStub:
    """audio_data on every RPC below is raw 32-bit float PCM samples (mono),
    NOT a WAV/container file -- i.e. exactly numpy.float32 bytes, matching
    the in-memory representation used throughout the Python pipeline
    (predict.py/preprocess.py). sample_rate describes those samples; the
    server resamples/preprocesses internally as needed. See
    grpc_client_test.py for the exact encode-side convention.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeAudio = channel.unary_unary(
                '/voiceguard.VoiceGuard/AnalyzeAudio',
                request_serializer=voiceguard__pb2.AudioRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.RiskResponse.FromString,
                _registered_method=True)
        self.AnalyzeWithContext = channel.unary_unary(
                '/voiceguard.VoiceGuard/AnalyzeWithContext',
                request_serializer=voiceguard__pb2.ContextualRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.RiskResponse.FromString,
                _registered_method=True)
        self.EnrollSpeaker = channel.unary_unary(
                '/voiceguard.VoiceGuard/EnrollSpeaker',
                request_serializer=voiceguard__pb2.EnrollRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.VerifyConsistency = channel.unary_unary(
                '/voiceguard.VoiceGuard/VerifyConsistency',
                request_serializer=voiceguard__pb2.VerifyRequest.SerializeToString,
                response_deserializer=voiceguard__pb2.ConsistencyResponse.FromString,
                _registered_method=True)


class VoiceGuardServicer:
    """audio_data on every RPC below is raw 32-bit float PCM samples (mono),
    NOT a WAV/container file -- i.e. exactly numpy.float32 bytes, matching
    the in-memory representation used throughout the Python pipeline
    (predict.py/preprocess.py). sample_rate describes those samples; the
    server resamples/preprocesses internally as needed. See
    grpc_client_test.py for the exact encode-side convention.

    """

    def AnalyzeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeWithContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollSpeaker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyConsistency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceGuardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAudio,
                    request_deserializer=voiceguard__pb2.AudioRequest.FromString,
                    response_serializer=voiceguard__pb2.RiskResponse.SerializeToString,
            ),
            'AnalyzeWithContext': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeWithContext,
                    request_deserializer=voiceguard__pb2.ContextualRequest.FromString,
                    response_serializer=voiceguard__pb2.RiskResponse.SerializeToString,
            ),
            'EnrollSpeaker': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollSpeaker,
                    request_deserializer=voiceguard__pb2.EnrollRequest.FromString,
                    response_serializer=voiceguard__pb2.EnrollResponse.SerializeToString,
            ),
            'VerifyConsistency': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyConsistency,
                    request_deserializer=voiceguard__pb2.VerifyRequest.FromString,
                    response_serializer=voiceguard__pb2.ConsistencyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voiceguard.VoiceGuard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voiceguard.VoiceGuard', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceGuard:
    """audio_data on every RPC below is raw 32-bit float PCM samples (mono),
    NOT a WAV/container file -- i.e. exactly numpy.float32 bytes, matching
    the in-memory representation used throughout the Python pipeline
    (predict.py/preprocess.py). sample_rate describes those samples; the
    server resamples/preprocesses internally as needed. See
    grpc_client_test.py for the exact encode-side convention.

    """

    @staticmethod
    def AnalyzeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.VoiceGuard/AnalyzeAudio',
            voiceguard__pb2.AudioRequest.SerializeToString,
            voiceguard__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeWithContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.VoiceGuard/AnalyzeWithContext',
            voiceguard__pb2.ContextualRequest.SerializeToString,
            voiceguard__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrollSpeaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.VoiceGuard/EnrollSpeaker',
            voiceguard__pb2.EnrollRequest.SerializeToString,
            voiceguard__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyConsistency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voiceguard.VoiceGuard/VerifyConsistency',
            voiceguard__pb2.VerifyRequest.SerializeToString,
            voiceguard__pb2.ConsistencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
